### ISSUE TITLE
Various errors, probably user error

### ISSUE THREAD

**Issue by Aoshira** [Coosanta17/crafty_discord_bot#4]
Hi, I'm new to Linux, Discord bots and basically everything to do with this project. I tried setting this bot up and the prerequisite steps worked fine but when I run `node .` I receive errors that are kinda unreadable to me:

Fetching application info...
Stop command is disabled.
Interval "autoStopInterval" started.
Restored existing or missing interval.
Checking if application (/) commands need updating...
No update needed.
/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:2                                                                                                                        76
      const err = new Error(`Unhandled 'error' event emitted, received ${stringifiedError}`);
                  ^

Error: Unhandled 'error' event emitted, received [object Object]
    at WebSocketShard.emit (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/@vladfrangu/async_ev                                                                                                                        ent_emitter/dist/index.cjs:276:19)
    at WebSocketShard.onClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/@discordjs/ws/dis                                                                                                                        t/index.js:1148:14)
    at connection.onclose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/@discordjs/ws/dist/in                                                                                                                        dex.js:686:17)
    at callListener (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/event-target.js:290:                                                                                                                        14)
    at WebSocket.onClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/event-target.js                                                                                                                        :220:9)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emitClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/websocket.js:                                                                                                                        272:10)
    at TLSSocket.socketOnClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/websocket                                                                                                                        .js:1341:15)
    at TLSSocket.emit (node:events:529:35)
    at node:net:351:12 {
  context: {
    error: Error: Used disallowed intents
        at WebSocketShard.onClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/@discordjs/ws                                                                                                                        /dist/index.js:1149:18)
        at connection.onclose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/@discordjs/ws/dis                                                                                                                        t/index.js:686:17)
        at callListener (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/event-target.js:                                                                                                                        290:14)
        at WebSocket.onClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/event-targe                                                                                                                        t.js:220:9)
        at WebSocket.emit (node:events:517:28)
        at WebSocket.emitClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/websocket                                                                                                                        .js:272:10)
        at TLSSocket.socketOnClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot/node_modules/ws/lib/webso                                                                                                                        cket.js:1341:15)
        at TLSSocket.emit (node:events:529:35)
        at node:net:351:12
        at TCP.done (node:_tls_wrap:657:7)
  }
}

Node.js v18.19.1

Do you have an idea what I could be doing wrong?

**Comment by Coosanta17** [comment]
Hi, it looks like your node.js version is outdated, try updating to version 20 or higher (I use 20.13.1). Also make sure you download the bot from the releases page rather than the source code as it is still experimental (and currently broken as of writing 😂).

**Comment by Aoshira** [comment]
Thanks for your help!

Unfortunately I think I'm still doing something wrong.
So I removed the old installation of the bot by deleting the folder. Then I removed node.js via command line and then installed a newer version of node.js.
To install the release of the bot I downloaded the Source.zip file, unpacked it into a folder and put that in my desired directory.
When I run npm install this is what I get (which didn't happen before):

``` 
andre@bisios:/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0$ sudo npm install

added 85 packages, and audited 86 packages in 831ms

48 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
``` 

When I try `npm audit fix --force` I get:
```
andre@bisios:/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0$ sudo npm audit fix --force
npm warn using --force Recommended protections disabled.
npm warn audit Updating axios to 1.3.1, which is a SemVer major change.

changed 1 package, and audited 86 packages in 1s

48 packages are looking for funding
  run `npm fund` for details

# npm audit report

axios  1.0.0 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix`
node_modules/axios

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix
```
So I used npm-check-updates and updated axios and tried again but the same problem persisted.

Then I just ran `node .` again to no avail:
```
andre@bisios:/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0$ sudo node .
Fetching application info...
Interval "autoStopInterval" started.
Restored existing or missing interval.
Checking if application (/) commands need updating...
No update needed.
/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0/node_modules/@discordjs/ws/dist/index.js:1149
          error: new Error("Used disallowed intents")
                 ^

Error: Used disallowed intents
    at WebSocketShard.onClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0/node_modules/@discordjs/ws/dist/index.js:1149:18)
    at connection.onclose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0/node_modules/@discordjs/ws/dist/index.js:686:17)
    at callListener (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0/node_modules/ws/lib/websocket.js:272:10)
    at TLSSocket.socketOnClose (/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0/node_modules/ws/lib/websocket.js:1341:15)
    at TLSSocket.emit (node:events:531:35)
    at node:net:339:12
    at TCP.done (node:_tls_wrap:657:7)

Node.js v20.16.0
```
At least it's a bit better 😅
Oh and I also tried version 20.13.1 but it didn't change anything

**Comment by Coosanta17** [comment]
It looks like there was an oversight in the setup instructions on my behalf, sorry about that! 

In discord developer portal, under the privileged gateway intents turn on "Message content intents". If that doesn't work try allowing all intents.

**Comment by Aoshira** [comment]
Alright, now we're getting somewhere 🙂
```
andre@bisios:/mnt/Internal25/Minecraft/Discordbot/crafty_discord_bot-1.0$ node .
Fetching application info...
Interval "autoStopInterval" started.
Restored existing or missing interval.
Checking if application (/) commands need updating...
No update needed.
Vikingsbot#2584 is online!
```
And then I can use `/start` as expected and the server starts up.
```
Attempting to start server.
Success!
Interval "autoStopInterval" started.
```
At this point the bot still shows as online in Discord.
But as soon as I enter another command (doesn' matter if it's `/help`or`/start`) Discord tells me 

> The application did not respond

 and around 30s after that Discord realizes that the bot has gone offline.

When I restart the bot using `node .`the same happens again. But before shutting down the MC server I can freely spam the `/help`command whithout the bot going offline.

**Comment by Coosanta17** [comment]
This is quite strange and I cannot recreate this, is there any other log sent? Also does the command entry prompt appear or it is hidden (does the process keep on running) after the bot stops responding? It might be a timeout but that should be logged. Or possibly a crafty controller permission error but it started up fine. Another possibility is server overload, if you host the bot on the same server as the Crafty instance it could lag the discord bot to timeout however the bot is quite lightweight and shouldn't lag unless the server is at its extreme limit.

It is quite strange that the bot crashed with no logs. Sorry about the inconvenience.

**Comment by Aoshira** [comment]
I really don't know what changes but now everything is working as expected. Here is what I did:

- Mc server was running
- I started the bot
- That's it xD

The only things that actually changed are that I was connected via wifi and not mobile data and that I installed two mods [dynmap](https://modrinth.com/plugin/dynmap) and [disconnect-packet-fix](https://modrinth.com/mod/disconnect-packet-fix/). But I highly doubt any of these things had any effect. So yeah, no idea why it wasn't working before.

Once again thank you so much for your help :)

**Comment by Aoshira** [comment]
Okay, I think I kinda know what is happening:
The bot keeps on running as long as I leave the terminal open, as soon as I close it the bot also gets disabled.

So yeah, I'm sure that is some misunderstanding on my part of the way these programs run. I assumed I basically just give the initial command to the bot and can then close the terminal. But it seems that shuts down the process as well.

I hope I'm making sense here, can you help me out once more?

**Comment by Coosanta17** [comment]
Sure, if you're using a linux desktop environment like gnome you can set it to open on server startup, it will open in a hidden terminal on server startup (when you turn the machine that is hosting crafty controller on - not minecraft server). Or you can use [screen](https://linuxize.com/post/how-to-use-linux-screen/) or [tmux](https://hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/) (I use tmux - screen is simpler but less sophisticated) and disown/detach the process so you can close the terminal. This should work on any linux distro and environment, with or without a desktop.

**Comment by Aoshira** [comment]
Once again, thank you so much! 🙏
Now everything is working perfectly
